title: Pysprings
description: Southern Colorado's Python User Group in Colorado Springs
baseurl: ""
url: "https://pysprings.org"
repository: pysprings/pysprings.github.io

# Build settings
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
